/** immunization - create and populate the immunization table.
*/
insert into cdm_status (task, start_time) select 'immunization', sysdate from dual
/
BEGIN
PMN_DROPSQL('DROP TABLE immunization');
END;
/

CREATE TABLE IMMUNIZATION ( 
    "IMMUNIZATIONID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PATID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"ENCOUNTERID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PROCEDURESID" VARCHAR2(20 BYTE), 
	"VX_PROVIDERID" VARCHAR2(20 BYTE), 
	"VX_RECORD_DATE" DATE, 
	"VX_ADMIN_DATE" DATE, 
	"VX_CODE_TYPE" VARCHAR2(2 BYTE), 
	"VX_CODE" VARCHAR2(20 BYTE), 
	"VX_STATUS" VARCHAR2(2 BYTE), 
	"VX_STATUS_REASON" VARCHAR2(2 BYTE), 
	"VX_SOURCE" VARCHAR2(2 BYTE), 
	"VX_DOSE" NUMBER(15,8), 
	"VX_DOSE_UNIT" VARCHAR2(20 BYTE), 
	"VX_ROUTE" VARCHAR2(20 BYTE), 
	"VX_BODY_SITE" VARCHAR2(20 BYTE), 
	"VX_MANUFACTURER" VARCHAR2(40 BYTE), 
	"VX_LOT_NUM" VARCHAR2(20 BYTE), 
	"VX_EXP_DATE" DATE, 
	"RAW_VX_NAME" VARCHAR2(50 BYTE), 
	"RAW_VX_CODE" VARCHAR2(20 BYTE), 
	"RAW_VX_CODE_TYPE" VARCHAR2(20 BYTE), 
	"RAW_VX_DOSE" VARCHAR2(20 BYTE), 
	"RAW_VX_DOSE_UNIT" VARCHAR2(20 BYTE), 
	"RAW_VX_ROUTE" VARCHAR2(20 BYTE), 
	"RAW_VX_BODY_SITE" VARCHAR2(50 BYTE), 
	"RAW_VX_STATUS" VARCHAR2(20 BYTE), 
	"RAW_VX_STATUS_REASON" VARCHAR2(20 BYTE), 
	"RAW_VX_MANUFACTURER" VARCHAR2(50 BYTE)
   );
/

update cdm_status
set end_time = sysdate, records = (select count(*) from immunization)
where task = 'immunization'
;
/
