WHENEVER SQLERROR CONTINUE;
DROP TABLE STATE_CODE;
WHENEVER SQLERROR EXIT SQL.SQLCODE;

CREATE TABLE STATE_CODE
   (
    "STATE" VARCHAR2(26 BYTE) NOT NULL ENABLE, 
	"CODE" VARCHAR2(26 BYTE) NOT NULL ENABLE
   )
; 
exit;
